# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
      - "../src/Tests/"

  ############ COMMON ############
  App\Common\Infrastructure\MySqlAdapterFactory: ~

  Doctrine\DBAL\Connection:
    factory: ['@App\Common\Infrastructure\MySqlAdapterFactory', create]
    arguments:
      - "%env(MYSQL_DATABASE)%"
      - "%env(MYSQL_USER)%"
      - "%env(MYSQL_PASSWORD)%"
      - "%env(MYSQL_HOST)%"
      - "%env(MYSQL_PORT)%"

  ############ CONTROLLERS ############
  App\Controller\Student\GetStudentsController:
    arguments:
      - '@App\Student\Application\GetStudents'
    tags: ["controller.service_arguments"]
  App\Controller\Student\CreateStudentController:
    arguments:
      - '@App\Student\Application\CreateStudent'
    tags: ["controller.service_arguments"]

  ############ USE CASES ##############
  App\Student\Application\GetStudents:
    arguments:
      - '@App\Students\Infrastructure\MySqlStudentRepository'
  App\Student\Application\CreateStudent:
    arguments:
      - '@App\Students\Infrastructure\MySqlStudentRepository'

  ############ REPOSITORIES ############
  App\Students\Infrastructure\MySqlStudentRepository:
    arguments:
      - '@Doctrine\DBAL\Connection'
